#!/bin/bash
# This script is a derivative work of the code from the following projects:
# Galactrum - https://www.galactrum.org/
# Innova Coin - https://innovacoin.info/
# and this copy was pulled from github user Drhobbi

# Modified for zerodb coin by ak3

REL="$(lsb_release -rs)"

clear
cd ~
echo "**********************************************************************"
echo "* OS: Ubuntu ${REL}                                                   *"
echo "*                                                                    *"
echo "* This script will install and configure your zerodb masternode.     *"
echo "*                                                                    *"
echo "* This script is provided 'AS IS' without any warranties or support. *"
echo "*                                                                    *"
echo "**********************************************************************"
echo && echo && echo
sleep 3

read -e -p "This script will install & configure a zerodb-Coin Masternode.  This script is supplied 'AS IS' without any warranties and support. Do you wish to continue? (y/n)? " response

if [[ "$response" =~ ^([yY][eE][sS]|[yY])+$ ]]; then
    
    # Gather input from user
    read -e -p "Masternode Private Key (e.g. 7edfjLCUzGczZi3JQw8GHp434R9kNY33eFyMGeKRymkB56G4324h) : " key
    if [[ "$key" == "" ]]; then
        echo "WARNING: No private key entered, exiting!!!"
        echo && exit
    fi
    read -e -p "Server IP Address (Without Port): " ip
    echo && echo "Pressing ENTER will use the default value for the next prompts."
    echo && sleep 3
    read -e -p "Add swap space? (Recommended) [Y/n] : " add_swap
    if [[ ("$add_swap" == "y" || "$add_swap" == "Y" || "$add_swap" == "") ]]; then
        read -e -p "Swap Size [4G] : " swap_size
        if [[ "$swap_size" == "" ]]; then
            swap_size="4G"
        fi
    fi    
    read -e -p "Install Fail2ban? (Recommended) [Y/n] : " install_fail2ban
    read -e -p "Install UFW and configure ports? (Recommended) [Y/n] : " UFW
    
    # Add swap if needed
    if [[ ("$add_swap" == "y" || "$add_swap" == "Y" || "$add_swap" == "") ]]; then
        if [ ! -f /swapfile ]; then
            echo && echo "Adding swap space..."
            sleep 3
            sudo fallocate -l $swap_size /swapfile
            sudo chmod 600 /swapfile
            sudo mkswap /swapfile
            sudo swapon /swapfile
            echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab
            sudo sysctl vm.swappiness=10
            sudo sysctl vm.vfs_cache_pressure=50
            echo 'vm.swappiness=10' | sudo tee -a /etc/sysctl.conf
            echo 'vm.vfs_cache_pressure=50' | sudo tee -a /etc/sysctl.conf
        else
            echo && echo "WARNING: Swap file detected, skipping add swap!"
            sleep 3
        fi
    fi
    
    # Update system 
    echo && echo "Upgrading system..."
    sleep 3
    sudo apt-get -y update
    sudo apt-get -y dist-upgrade
    
    # Add Berkely PPA
    echo && echo "Installing bitcoin PPA..."
    sleep 3
    sudo apt-get -y install software-properties-common pwgen unzip libevent-dev libgmp3-dev libssl-dev bsdmainutils nano htop pwgen
    sudo apt-add-repository -y ppa:bitcoin/bitcoin
    sudo apt-get -y update
    
    # Install required packages
    echo && echo "Installing base packages..."
    sleep 3
    sudo apt-get -y install \
        libboost-all-dev \
        libdb4.8-dev \
        libdb4.8++-dev
    if [ "16.04" == "${REL}" ]; then
    sudo apt-get -y install libzmq5 libminiupnpc10
    else
    sudo apt-get -y install libzmq3 libminiupnpc8
    fi

    # Install fail2ban if needed
    if [[ ("$install_fail2ban" == "y" || "$install_fail2ban" == "Y" || "$install_fail2ban" == "") ]]; then
        echo && echo "Installing fail2ban..."
        sleep 3
        sudo apt-get -y install fail2ban
        sudo service fail2ban restart 
    fi
    
    # Install firewall if needed
    if [[ ("$UFW" == "y" || "$UFW" == "Y" || "$UFW" == "") ]]; then
        echo && echo "Installing UFW..."
        sleep 3
        sudo apt-get -y install ufw
        echo && echo "Configuring UFW..."
        sleep 3
        sudo ufw default deny incoming
        sudo ufw default allow outgoing
        sudo ufw allow ssh
        sudo ufw limit ssh/tcp
        sudo ufw allow 43101/tcp
        sudo ufw logging on
        echo "y" | sudo ufw enable
        echo && echo "Firewall installed and enabled!"
    fi

    # Download zerodb-Coin
    echo && echo "Downloading zerodb-Coin archive"
    sleep 3
    cd ~
    wget -t0 -c "https://guac.marcthespot.com/zerodb.zip"
    unzip -u "zerodb.zip"

    chmod +x ~/zerodb-cli ~/zerodbd
    sudo cp -f ~/zerodb-cli /usr/local/bin
    sudo cp -f ~/zerodbd /usr/local/sbin

    #Checking if we are under root user and creating unpriviliged account
    myuser="$(whoami)"
    zerodbuser="zerodb"

    #Creating zerodb unprivileged user for zerodb daemon
    echo && echo "Creating 'zerodb' unprivileged user"
    sudo useradd ${zerodbuser} -s /usr/sbin/nologin

    #Creating configuration directory
    echo && echo "Creating configuratoin directory"
    sudo mkdir -p /home/${zerodbuser}/.zerodb
    sudo chown ${myuser}:${zerodbuser} -R /home/${zerodbuser}
    sudo chmod 770 -R /home/${zerodbuser}


    datadir="-datadir=/home/${zerodbuser}/.zerodb"
    OPTIONS="${datadir} -daemon"

    #Adding aliases
    echo -e "\nalias zerodb-cli='sudo -u ${zerodbuser} zerodb-cli ${datadir}'\nalias zerodbd='sudo -u ${zerodbuser} zerodbd ${datadir}'\n" >> ~/.bash_aliases
    . ~/.bash_aliases

    # Create config for zerodb-Coin
    echo && echo "Configuring zerodb-Coin..."
    sleep 3

    sudo -u ${zerodbuser} zerodbd ${OPTIONS} >/dev/null 2>&1
    sleep 5

    sudo chown ${myuser}:${zerodbuser} /home/${zerodbuser}/.zerodb/zerodb.conf

    rpcuser=`cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1`
    rpcpass=`pwgen -1 20 -n`

    echo -e "maxconnections=256\nrpcuser=${rpcuser}\nrpcpassword=${rpcpass}\nrpcallowip=127.0.0.1\nrpcthreads=8\nlisten=1\nserver=1\ndaemon=1\nstaking=0\ndiscover=1\nexternalip=${ip}:55999\nmasternode=1\nmasternodeprivkey=${key}\naddnode=209.250.242.79:43101\naddnode=45.77.216.199:43101" > /home/${zerodbuser}/.zerodb/zerodb.conf

    echo && echo "Starting zerodb-Coin daemon"
    sudo -u ${zerodbuser}  zerodbd ${OPTIONS}

    cd ~
    echo && echo && echo
    echo "zerodb installation completed successfully.  Please wait 15 minutes and then start your masternode from your local wallet"
else
    echo "installation cancelled"
fi

